name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Setiap hari jam 00:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: YammD123
          outputs: |
            ./dist/pacman-contribution-graph.svg
            ./dist/pacman-contribution-graph-dark.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
